process based parallelism, progress bar returned, 30% speed up
roblabs/gdal2tilesp pull request #6
Opened 2017-02-01 11:47 UTC by bolshoydi

When make pool.join () my os is hanging. so i decided to do job with process based parallelism. And its worked for me. Furthermore this method gave me processing time improvement.

2017-02-01 16:15 UTC, roblabs requested changes
@bolshoydi , every line changed, this is likely due to tabs settings in the Python editor.  Is it possible to check the white space settings and recommit?  I know thats a pain, but then others cannot see what changes you made, and we won't be able to push it upstream to the original repo.

I did try your branch and received these errors on macOS.

Do I have a similar version of Python or GDAL as you?

### Git
``` bash
git checkout -b bolshoydi-windows_256 master
git pull https://github.com/bolshoydi/gdal2tilesp.git windows_256
```

### Go
``` bash
python gdal2tilesp.py -z 11-15 whitney.vrt
``` 

### Output
``` bash
Generating Base Tiles:
0...10...20...30...40...50...60...70...80...90...100 - done.
exception error:  Traceback (most recent call last):
  File "gdal2tilesp.py", line 2643, in worker_base_tiles
    gdal2tiles.generate_base_tiles(cpu, queue)
  File "gdal2tilesp.py", line 1382, in generate_base_tiles
    band_list=list(range(1, self.dataBandsCount + 1)))
  File "/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages/osgeo/gdal.py", line 1916, in ReadRaster
    resample_alg, callback, callback_data )
RuntimeError: Illegal values for buffer size



Generating Overview Tiles:
Something Wrong:  Traceback (most recent call last):
  File "gdal2tilesp.py", line 2652, in worker_overview_tiles
    gdal2tiles.generate_overview_tiles(cpu, tz, queue)
  File "gdal2tilesp.py", line 1508, in generate_overview_tiles
    gdal.GA_ReadOnly)
RuntimeError: whitney/15/16383/16383.png: No such file or directory

Something Wrong:  Traceback (most recent call last):
  File "gdal2tilesp.py", line 2652, in worker_overview_tiles
    gdal2tiles.generate_overview_tiles(cpu, tz, queue)
  File "gdal2tilesp.py", line 1508, in generate_overview_tiles
    gdal.GA_ReadOnly)
RuntimeError: whitney/14/8191/8191.png: No such file or directory

Something Wrong:  Traceback (most recent call last):
  File "gdal2tilesp.py", line 2652, in worker_overview_tiles
    gdal2tiles.generate_overview_tiles(cpu, tz, queue)
  File "gdal2tilesp.py", line 1508, in generate_overview_tiles
    gdal.GA_ReadOnly)
RuntimeError: whitney/13/4095/4095.png: No such file or directory

Something Wrong:  Traceback (most recent call last):
  File "gdal2tilesp.py", line 2652, in worker_overview_tiles
    gdal2tiles.generate_overview_tiles(cpu, tz, queue)
  File "gdal2tilesp.py", line 1508, in generate_overview_tiles
    gdal.GA_ReadOnly)
RuntimeError: whitney/12/2047/2047.png: No such file or directory

```

2017-02-02 10:23 UTC, bolshoydi commented
About all lines have been edited - it is because of i've made all changes on my offline computer. so in online computer with old commit i just replaced  file by new one. Sorry for this mistake i will try repair it soon.
`RuntimeError: Illegal values for buffer size` I haven't seen such error. I'm using python 2.7.10 x64 on win 7 platform and GDAL 2.0.0

2017-02-02 16:59 UTC, roblabs approved these changes

2017-02-02 17:08 UTC, roblabs approved these changes
@bolshoydi , thanks for the rework and initial work!

2017-02-02 17:13 UTC, merged